cloudfoundry/haproxy-boshrelease

jobs/haproxy/templates/haproxy.config.erb
Hi,
If I want to use only the port 80 as proxy (default) behind an ELB the forwarded proto should be pass, be cause some application can require this proto.
Example : 
ELB 80,443,4433--> 80 Haproxy --> 80 router  --> my app
If I query https://mydomain.com the ELB will give the https as forwarder-proto but haproxy still send http, my app is expecting https so I will send a redirect to https  .... so I will loop.
=> Add forward-proto-header

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, jobs/haproxy/templates/ssl_redirect.map.erb
Following two options are possible now:
- Set property "ha_proxy.https_redirect_all" to true, redirects all requests to https
- Set property "ha_proxy.https_redirect_domains" to an array of domains, all requests to one of these domains will be redirected to https (including ALL subdomains)
This feature is using map-feature of haproxy to provide a high performance for a high number of domains in the list
=> Fixed Issue #10

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, packages/haproxy/packaging, packages/haproxy/spec
It is possible now to enable gzip compression for specific mime types. Therefore set property "ha_proxy.compress_types" to a String like "text/html text/plain text/css"
Also fixed a version conflict between packages/haproxy/packaging and packages/haproxy/spec files
=> Fixed issue #11

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
I needed the ability to have haproxy balance to multiple backend services based on the URL. This is the solution I came up with to try and get this merged upstream. The other option is to allow an escape hatch for users to provide their own config in their manifest but I thought this would be less invasive.
=> Add capability to have multiple backends based off of URL path prefix

README.md
Fixes #7. Not sure where 'bosh verify deployment' came from.
=> Removed 'bosh verify deployment' from the readme

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
Added support for having HAProxy set headers on each
HTTP request, based on the `ha_proxy.headers` property.
@shinji62 Can you let me know what you think of this?
=> Added support for forcing headers on requests

jobs/haproxy/spec, jobs/haproxy/templates/cert.pem.erb, jobs/haproxy/templates/certs.ttar.erb, jobs/haproxy/templates/haproxy.config.erb, jobs/haproxy/templates/haproxy_ctl, packages/ttar/packaging, packages/ttar/spec
Added support to provide `haproxy.ssl_pem` as an array
of certs, to enable users to serve multiple https domains through
haproxy. If `haproxy.ssl_pem` is specified as a string, a single
cert is create, the same as before. If it is an array, each element
is treated as a separate cert, which gets loaded into haproxy.
=> Added support for multiple ssl certificates

ci/release_notes.md, jobs/haproxy/templates/haproxy.config.erb
#Bugfix
Http Redirect code snippet (https_redirect_all) is outside the disable_http block.
Due to this, it is not possible to disable http interface.
=> Correcting the end tag for http block

ci/release_notes.md, jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
Adding support for response headers in haproxy. The default header was supporting only request headers. Hardering parameters like HSTS needs response headers in haproxy
=> rspheaders added

ci/release_notes.md, jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
Use Case:
In the current haproxy both the cloudfoundry apps and cloudfoundry infrastructure management endpoints (like api, login, blobstore, loggregator) are exposed.
The cloudfoundry infrastructure management endpoints are used only by cloudfondry administrator, who operates from a pre-defined set of source ip's.
This feature is to restrict configured api endpoints to be accessible only from a fixed set of source ip's.
1) An acl is created with the src ips
2) Per api endpoint a http request deny is added, to deny the request for that api endpoint if the src ip address is not in the above acl.
=> Capability to restrict access to api endpoints.

jobs/haproxy/templates/haproxy.config.erb
In various locations, the path to the ssl certs are hardcoded to `/var/vcap/jobs/haproxy/config/ssl`. Only for wss-in the path was missing the config subdir.
Making the path variable might be interesting too, but I don't have time for that right now.
=> Corrected path to ssl certs for wss-in

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
* This would enable a socket interface for haproxy where you can pull off network level metrics for your haproxy. 
* The UI can be reached with {YOUR_PROXY_IP}:9000/haproxy_stats with the credentials you set.
=> enable socket level stats via port 9000

config/blobs.yml, jobs/haproxy/templates/haproxy.config.erb, packages/haproxy/packaging, packages/haproxy/spec
The haproxy package now comes with socat, and haproxy itself now
instantiates the stats socket in /var/vcap/sys/run/haproxy/stats.sock
Usage is pretty simple:
echo show errors | /var/vcap/packages/haproxy/bin/socat \
/var/vcap/sys/run/haproxy/stats.sock -
Fixes #40
=> Support haproxy stats socket / socat package

jobs/haproxy/templates/haproxy.config.erb
This was missed in a previous change to whitelist specific internal
network segments (via CIDR blocks).
=> Fix ACL for 4443/TLS

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
Current spec/config causes haproxy to crash before starting properly due to incorrect bind value (:9000)
=> Add stats_bind parameter support.

config/blobs.yml, docs/keepalived.md, jobs/keepalived/monit, jobs/keepalived/spec, jobs/keepalived/templates/keepalived.config.erb, jobs/keepalived/templates/keepalived_ctl, packages/keepalived/packaging, packages/keepalived/spec, templates/example-settings.yml, templates/jobs.yml
Adding support for [keepalived](http://www.keepalived.org/documentation.html) to enable high availability in an haproxy deployment, leveraging the https://en.wikipedia.org/wiki/Virtual_Router_Redundancy_Protocol more formally [RFC 5798](https://tools.ietf.org/html/rfc5798). See [keep-alived man page](https://linux.die.net/man/5/keepalived.conf) for more precision over capabilities of keep-alived as well as the [keep-alived user manual](http://www.keepalived.org/pdf/UserGuide.pdf)
This enables declaring a virtual IP (``keepalived.vip``) that will automatically fail over between the multiple haproxy VMs: the master will initially be the bosh vm for haproxy job instance 0. The default IP addresses assigned by bosh to vms on eth0 are used within the VRRP protocol.
Notes:
* this PR needs to …
=> Keepalived support

jobs/keepalived/monit, jobs/keepalived/spec, jobs/keepalived/templates/keepalived_ctl
- Log messages from the startup/shutdown, of keepalived
as well as keepalived itself go to /var/vcap/sys/log/keepalived.log
- The vrrp + checkers pid files are now located in /var/vcap/sys/run
- If the `keepalived.interface` property is set to `auto`, the job
will now auto-detect the default interface of the VM, and use that.
=> Improved keepalived operability

jobs/haproxy/templates/haproxy.config.erb
This change adds the first 20 characters of the 'Host' header to the log. It helps when you try to find out to which applications the requests are sent.
A shortened example of a line in the logfile. The captured host name is highlighted:
Jun 28 14:26:15 localhost haproxy[4812]: 52.52.52.52:1337 [28/Jun/2017:14:25:45.357] https-in~ http-routers/node0 30008/0/0/7/30015 200 1442 - - ---- 3/3/2/2/0 0/0 **{api.cf.cf-hcp-wot.aw}** "GET /internal/bulk/apps?batch_size=500&format=fingerprint&token={} HTTP/1.1"
=> Add hostname from Host header to http log

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
This optional parameter allows to set the number of haproxy threads started for each VM. This option helps to improve the performance - especially on multicore VMs.
=> Add option to set number of haproxy threads per VM

jobs/haproxy/spec, jobs/haproxy/templates/blacklist_cidrs.txt.erb, jobs/haproxy/templates/haproxy.config.erb, jobs/haproxy/templates/whitelist_cidrs.txt.erb
This pull request adds the feature to optionally provide a black- and whitelist for http(s) access.
The black- and whitelist each contain a list of CIDRs. A client is allowed to connect to http(s) if
- the IP is whitelisted **OR**
- the IP not blacklisted
You can provide the lists in two formats.
- as an inline yaml array. See: example in the spec file.
- as a gzipped and base64 encoded string (large files). See: [HAProxy - load patterns from a file '-f'](https://cbonte.github.io/haproxy-dconv/1.6/configuration.html#7.1) for details about the file format. 
The tcp connection is dropped at `content reject` rather then `connection reject` because the client ip is not available in the latter case if accept-proxy is used. See [HAProxy …
=> Add black- and whitelisting for http(s) access

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
The pull request adds the option to specify the load balancing algorithm for tcp backends. For example, this allows us to use leastconn algorithm for longer running sessions (such as SSH).
=> Add option to specify balance algorithm

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
This pull request adds the option to specify the buffer size to use for requests. The option enables increasing the buffer size to allow applications that require large cookies or query strings to function.
=> Add option to specify buffer size

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
The pull request adds the option to enable http health check on `haproxy_ip:8080/health`. The health check monitors the status of the http-routers. A failure is reported when all http-routers are down.
=> Add option to enable http health check on port 8080

jobs/haproxy/templates/certs.ttar.erb
This will strip leading and trailing whitespace before concatenating the certs and keys making sure they get formatted correctly.
Resolves https://github.com/cloudfoundry-incubator/haproxy-boshrelease/issues/72
=> Sanitizes cert/key pairs

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
The http health check for tcp backends can only be used for backends specified in the manifest, but not for dynamically linked backends: https://github.com/cloudfoundry-incubator/haproxy-boshrelease/blob/master/jobs/haproxy/templates/haproxy.config.erb#L374-L381
With this PR a link can either contain a `health_check_http` property or the (optional) global property `ha_proxy.tcp_link_health_check_http` is used.
=> Add support for http health check when using tcp_backend link

jobs/haproxy/spec, jobs/haproxy/templates/backend-crt.erb, jobs/haproxy/templates/haproxy.config.erb
This commit provides the capability to do mutual ssl with backend server.
The idea helps https://github.com/cloudfoundry-incubator/routing-release/blob/develop/jobs/gorouter/spec#L120
In forward mode (not always_forward): gorouter needs a client certificate from ha proxy to do mutual ssl
=> provides capabilities to do backend mutual ssl

.gitmodules
Since the repo is public cloning this repo should not require ssh
Signed-off-by: Andrew Crump <acrump@pivotal.io>
=> uses https instead of ssh to clone ttar submodule

jobs/haproxy/spec, jobs/haproxy/templates/client-ca-certs.erb, jobs/haproxy/templates/client-revocation-list.erb, jobs/haproxy/templates/haproxy.config.erb
The client certificate will be requested
If no cert prompt, the handshake still go through one way ssl
If a client certificate prompt, ha proxy will pass through and carry a header with cert base64 encoding
The header match what gorouter supports https://github.com/cloudfoundry-incubator/routing-release/blob/develop/jobs/gorouter/spec#L115   as x-forwarded-client-cert for mutual ssl purpose to backend apps
=> This is a commit to let haproxy to do mutual ssl

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
We would like to provide a port range  to simplify configuration needed for CF TCP routing when using HAProxy as the load balancer.
* Consumes `tcp_router` link from the [routing-release](https://github.com/cloudfoundry/routing-release/blob/d1e5369935688080e69335058922c2f0970dbfdb/jobs/tcp_router/spec#L18-L20).
* Adds `ha_proxy.tcp_routing.port_range` property to the `haproxy` job. This property is used only if `tcp_router` link is present.
The default value for the `ha_proxy.tcp_routing.port_range` property comes from [`cf-deployment`](https://github.com/cloudfoundry/cf-deployment/blob/43e9eb3fa9ab4f1e16659f6ec8f38811e12023a9/cf-deployment.yml#L732).
=> Add support for CF TCP Routing

jobs/keepalived/templates/keepalived_ctl, packages/keepalived/packaging, packages/keepalived/spec, src/common/utils.sh
Checker's pid is not tracked so it's process is not stopped.
PIDs are terminated without giving them a chance to end their children so these stay running as well.
=> Fixes for keepalived stop

jobs/keepalived/templates/keepalived_ctl
When property `keepalived.interface` is not set to auto, the keepalived.config is not generated and keepalived fails to start
=> Fix manual interface logic

jobs/haproxy/spec, jobs/haproxy/templates/certs.ttar.erb, jobs/haproxy/templates/haproxy.config.erb
Hi @geofffranks, 
as @jgf already mentioned in slack,I've prepared a pull request for the crt-list feature of haproxy-1.8.x. Only things that are already supported by the haproxy-boshrelease are now also supported by crt-lists. The one and only exception is the "verify" option.
The existing "ssl_pem" feature has not been touched, but if you put both "ssl_pem" and "crt_list" in your manifest, an error will be reported.
Please have a look at my changes.    
crt-list is documented here:
https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#5.1-crt-list
The new field 'haproxy.crt_list' replaces 'haproxy.ssl_pem' and allows to
specify sslbindconf and snifilter options for each certificate
Only a small subset of the allowed sslbindconf options is supported:
sslbindconf   | field in …
=> allow to use crt-list configurations

ci/release_notes.md, jobs/haproxy/spec, jobs/haproxy/templates/certs.ttar.erb, jobs/haproxy/templates/haproxy.config.erb
- The HTTP frontend now supports accept-proxy.
- Bugs where accept-proxy was not honored during mutual TLS have been
resolved
- `ha_proxy.client_cert` is no longer required to enable TLS. It is
still honored to enable mutual tls, but the boshrelease will also
use the presence of the following parameters to enable mutual TLS:
- `ha_proxy.client_ca_file`
- `ha_proxy.client_revocation_list`
- `ha_proxy.crt_list.<i>.client_ca_file`
- `ha_proxy.crt_list.<i>.client_revocation_list`
- `ha_proxy.crt_list.<i>.verify` - only when value is not "none"
- The following options are now honored in the `:4443` backend:
- `ha_proxy.cidr_whitelist`
- `ha_proxy.cidr_blacklist`
- `ha_proxy.block_all`
- `ha_proxy.hsts_*`
- `ha_proxy.rsp_headers`
- The X-Forwarded-Client_Cert now is set for requests in the …
=> Ensure frontend options are applied appropriately to all frontends

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
This allows for blocking http-requests according to
http://cbonte.github.io/haproxy-dconv/1.8/configuration.html#7.2
This commit supports conditions consisting of multiple rules
combined with the AND operator. The OR operator and negation
are note yest supported.
=> Add configuration for http-request deny conditions

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
I have a use case where port 8080 is already taken by another process that I cannot change. So I need to be able to configure the health check port of ha proxy.
I tested this change and it was working well on my GCP environment
=> Make health check port configurable

jobs/haproxy/templates/haproxy_ctl
Should read /var/vcap/packages/ttar/bin/ instead of /var/vcap/packges/ttar/bin/
=> Typo path packages

jobs/haproxy/templates/haproxy.config.erb
This change only appends the `X-Forwarded-Client-Cert` header in case the current SSL session uses a client certificate. See http://cbonte.github.io/haproxy-dconv/1.8/configuration.html#7.3.4-ssl_c_used
Previously an empty header field was added which can cause problems with some applications.
```
X-Forwarded-Client-Cert: ""
```
=> Only add X-Forwarded-Client-Cert header if client certificate is present

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
Adds the new option `forwarded_client_cert` to the haproxy boshrelease. This option lets you decide how the  X-Forwarded-Client-Cert (XFCC) header is handled. The options are similar to the ones from the gorouter (https://github.com/cloudfoundry-incubator/routing-release/blob/develop/jobs/gorouter/spec#L115-L125).
The related Issue #86 should be fixed.
From the new spec file:
`ha_proxy.forwarded_client_cert`:
This option lets you decide how to handle the X-Forwarded-Client-Cert (XFCC) http header on any https frontend. On http frontends the `always_forward_only` option is active by default and can't be changed. On https frontends your options are (ordered from least to most secure):
- `always_forward_only`:
Least secure option. Always forward the XFCC header in the request, regardless of …
=> Add option to forward or sanitize X-Forwarded-Client-Cert header

manifests/haproxy.yml
This PR contains 2 fixes:
The bpm release was missing
There is now only one (v9.4.0) haproxy release definied
=> bugfix missing bpm release and multiple haproxy version releases

jobs/keepalived/spec, jobs/keepalived/templates/keepalived.config.erb
We run into an issue where the vrrp vip is lost when DHCP lease is renwed due to OpenStack maintenance. This issue is described in more details [here](https://serverfault.com/questions/601670/keepalived-vip-removed-with-dhcp-renewal). 
This PR exposes the `dont_track_primary` which ignores VRRP interface faults.
=> Allow configuring dont_track_primary for keepalived

jobs/haproxy/spec, jobs/haproxy/templates/drain.erb, jobs/haproxy/templates/haproxy.config.erb
Currently, monit stop kills the haproxy processes and all established
connections are closed. A drain script is added to enable graceful
shutdown by sending a SIGUSR1 signal [1]. The script instructs bosh
to wait for a configurable period of time before it calls monit stop.
Draining is disabled by default
Additionally an option is added to allow frontends to accept new connections after SIGUSR1.
This is useful to give load balancers time to detect the failing health check.
[1] https://cbonte.github.io/haproxy-dconv/1.7/management.html#4
=> Add drain script to enable graceful shutdown

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, jobs/haproxy/templates/trusted_domain_cidrs.txt.erb
When the trusted_domain_cidrs list was too long haproxy start-up failed
with the following error:
parsing [/var/vcap/jobs/haproxy/config/haproxy.config:60]: line too long,
truncating at word 65, position 1049
Additionally trusted_domain_cidrs can be provided as a base64 encoded
string.
=> Read trusted_domain_cidrs from a file

jobs/haproxy/templates/haproxy_wrapper
Fixes issue #140
Fixes this error
```
/var/vcap/jobs/haproxy/bin/haproxy_wrapper: line 13: -f: command not found
```
Also added `|| true` to prevent script from exiting if the process could no longer be found.
=> Fix haproxy_wrapper cleanup_daemon

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, manifests/ops-files/protect-domain.yml
Hi,
i had to adjust the haproxy boshrelease to protect multiple domains with a whitelist.
The current status of the release only supports `ha_proxy.http_request_deny_conditions` which are not negetable. I can blacklist certain ips for a domain that i protect through acl's like so:
```
- type: replace
path: /instance_groups/name=haproxy/jobs/name=haproxy/properties?/ha_proxy?/http_request_deny_conditions?/-
value:
condition:
- acl_name: foobar.com_domain
acl_rule: "hdr(host) -i foobar.com"
- acl_name: foobar.com_blacklist
acl_rule: >-
src
127.0.0.1
127.0.0.2
```
But on the other hand i cannot provide a whitelist of ips since this would require to negate the acl condition that contains the src statement.
This PR tries to solve this problem by adding an optional negate flag to the …
=> negation flag for http_request_deny_conditions acl conditions

jobs/haproxy/templates/drain.erb
Too verbose, probably leftover from debugging.
=> Remove leftover `-x` bash opt

jobs/haproxy/templates/drain.erb
With bpm 1.1.0 `haproxy_wrapper` is not started directly, but indirectly through [`tini`](https://github.com/cloudfoundry/bpm-release/commit/49d8ede5fc240cc3f135071aaadf19081e038182).
This breaks the functionality of the drain script, since `grep haproxy` also matches `haproxy_wrapper` which leads to a non graceful shutdown.
bpm 1.0.0:
```
haproxy/c2cdb159-9289-45ed-a223-a7d6ec608b8c:~$ ps aux | grep haproxy
vcap      4724  0.0  0.0  19708  3380 ?        S<s  12:01   0:00 /bin/bash /var/vcap/jobs/haproxy/bin/haproxy_wrapper
vcap      4753  0.1  0.3  49440 15052 ?        S<s  12:01   0:00 /var/vcap/packages/haproxy/bin/haproxy -f /var/vcap/jobs/haproxy/config/haproxy.config -D -p /var/vcap/sys/run/haproxy/haproxy.pid
bosh_9d+  4873  0.0  0.0  12944  1008 pts/0    S+   12:04   0:00 grep …
```
=> Fix drain script for bpm v1.1.0

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy_templates_spec.rb
Cross-AZ traffic will cause extra costs on iaas providers like AWS, therefore prefer traffic to local AZs.
This will be implemented via backup server, which will get called only if the remaining regular servers are down
=> add feature to avoid cross-az traffic

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy_templates_spec.rb
We introduce a new manifest property to the `haproxy` job, `ha_proxy.v4v6`, which propagates the HAProxy configuration directive, [`v4v6`](https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#5.1-v4v6), which, when the `binding_ip` is set to `::` (bind to every IPv6 interface, i.e. [`in6addr_any`](http://man7.org/linux/man-pages/man7/ipv6.7.html)), will also bind to every IPv4 interface (i.e. 0.0.0.0, `INADDR_ANY`).
This should have **no affect** on existing manifests. This should have no effect on existing behavior (unless the property is enabled): The new property, `v4v6`, is disabled by default. Furthermore, it will _only_ be instantiated if the `haproxy.binding_ip` is set to `::`.
Includes test for new property.
This feature would be useful in dual-stack environments (both …
=> Enable simultaneous binding to IPv4+IPv6 interfaces

jobs/haproxy/templates/bpm.yml
since the bpm adoption, the property ha_proxy.syslog_server does not make sense in case a local unix socket from the root filesystem should get integrated. Therefore this property needs to be configurable to make the path visible inside the container
=> make bpm log path configurable

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
HAProxy stats can be enabled without authentication. 
With this PR the HAProxy-boshrelease could have the same functionality by making the user and password optional.
Additionally, authentication doesn't make sense when the service is bind to localhost and when the trusted_stats_cidrs is limited to 127.0.0.1
=> Make HAProxy stat authentication optional

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
Reverts cloudfoundry-incubator/haproxy-boshrelease#144
=> Revert "Make HAProxy stat authentication optional"

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, jobs/haproxy/templates/haproxy_wrapper, jobs/haproxy/templates/reload
This will enable seamless reloads of HAproxy without draining and re-deploying via BOSH.
For background info see https://www.haproxy.com/blog/hitless-reloads-with-haproxy-howto/
Background:
We would like to reload HAproxy without stopping it and losing all connections. HAproxy should only be restarted if there is a new version or a stemcell update.
Since there is no such thing as "reload" in either the BOSH lifecycle or BPM lifecycle, we will keep this as a special case and don't want to disrupt the existing deployment mechanism.
Adding this will allow us to seamlessly reload HAproxy without dropping a single connection (as long a there are no changes in the BOSH manifest of course).
I've added a signal handler to the haproxy_wrapper that reloads haproxy as described in …
=> Add support for hitless reloads

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
The tune.maxrewrite parameter [1] is used to configure space for header
rewriting or appending.
We observed that for large requests and high load the x-forwarded-client-cert
header was not added to the request when using sanitize_set. Increasing
tune.maxrewrite solved the issue.
[1] https://cbonte.github.io/haproxy-dconv/1.9/configuration.html#tune.maxrewrite
=> Add configuration for tune.maxrewrite

docs/external_certs.md, jobs/haproxy/spec, jobs/haproxy/templates/certs.ttar.erb, jobs/haproxy/templates/haproxy_wrapper, jobs/haproxy/templates/haproxy_wrapper.erb, jobs/haproxy/templates/pre-start.erb
This PR provides the capability to add an additional source of external certificates to HAproxy.
The major use-case is to support CF-based platforms that allow their customers to register domains  and use their own certificates. These certificates may come at any time and usually happen outside the regular BOSH deploy/update lifecycle. In conjunction with the "hitless reloads" feature (see #159 ), this allows an external service to provide an additional list of certificates and dynamically load them into HAproxy without downtime.
=> Add support for additional external certificates

manifests/haproxy.yml
Hi there,
I added the BPM URL + SHA to the manifest that makes it possible for the BOSH director to download the release by itself rather than making the operator to download and upload it manually.
Please find the URL + SHA information here: https://bosh.io/releases/github.com/cloudfoundry/bpm-release?all=1
=> [manifests] Add sha + url bpm to make it downloadable for BOSH

jobs/haproxy/monit
This PR fixes an issue that can occur when using the `ext_crt_list` feature with `ext_crt_list_policy` set to `fail`.
If loading the additional certificates does not work in time, the HAproxy won't be started. However, from monits perspective it is running because monit only watches the `haproxy_wrapper` script (which is doing the timeout and waiting for certificates).
So if there is a persistent issue with the external certificates not getting delivered, BOSH will end up deploying all HAproxy instances, none of which are actually running in the end, thus producing an outage.
The fix to this problem is to watch not just the process but also if you can actually talk to the proxy. We accomplish this by checking the http health port in addition to the pid.
=> Add monit section for health check

config/blobs.yml, jobs/haproxy/templates/pre-start.erb, packages/haproxy/packaging
Fixes #160 
- Update hatop to v0.8 to provide support for python3
- Add symlink to hatop-wrapper for convenience
- Add symlink to python3 in case only python3 exists
=> Hatop python fix

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
We have Haproxy terminating TLS and then Gorouter behind Haproxy. We want to use Mutual TLS with Route Services. Right now this is broken, because Gorouter makes an external request to the route service, and Haproxy's `sanitize_set` option strips off the `X-Forwarded-Client-Cert` header.
This commit adds a new setting `forwarded_client_cert: forward_only_if_route_service`. In this mode Haproxy will preserve X-Forwarded-Client-Cert headers if there is also a X-Cf-Proxy-Signature header provided.
The security of this is based on Gorouter verifying the contents of the X-Cf-Proxy-Signature header. [Gorouter checks the contents of that header and rejects the request if it did not come from a CF Route Service](https://docs.cloudfoundry.org/services/route-services.html#x-cf-proxy-signature) …
=> New Mutual TLS setting compatible with CF Route Services

acceptance-tests/bosh_helpers.go, acceptance-tests/config.go, acceptance-tests/healthcheck_test.go, acceptance-tests/http_frontend_test.go, acceptance-tests/https_ext_crt_list.go, acceptance-tests/https_frontend_test.go, acceptance-tests/tcp_frontend_test.go, acceptance-tests/xfcc_test.go, jobs/haproxy/monit, jobs/haproxy/spec
Fixes #195 
Requires https://github.com/cloudfoundry-incubator/haproxy-boshrelease/pull/192 is merged first
With this change deployments with unhealthy backends will fail with:
```
Task 6 | 12:30:42 | L starting jobs: haproxy/aff24934-0f1c-4cb4-8061-8654b8206eb1 (0) (canary) (00:00:40)
L Error: 'haproxy/aff24934-0f1c-4cb4-8061-8654b8206eb1 (0)' is not running after update. Review logs for failed jobs: haproxy-health
Task 6 | 12:31:14 | Error: 'haproxy/aff24934-0f1c-4cb4-8061-8654b8206eb1 (0)' is not running after update. Review logs for failed jobs: haproxy-health
```
=> Ensure that deployment fails when enable_health_check_http: true and there are no healthy backends

acceptance-tests/acceptance_tests_suite_test.go, acceptance-tests/access_control_test.go, acceptance-tests/remote.go, jobs/haproxy/spec
~Requires https://github.com/cloudfoundry-incubator/haproxy-boshrelease/pull/198 is merged first~
Implement acceptance tests for `ha_proxy.cidr_whitelist` and `ha_proxy.cidr_blacklist` properties
Also clarifies the spec description for `ha_proxy.cidr_whitelist`
=> Implement ACL acceptance tests

acceptance-tests/https_ext_crt_list_test.go, ci/scripts/lint, jobs/haproxy/spec, jobs/haproxy/templates/certs.ttar.erb, spec/haproxy/templates/certs.ttar_spec.rb
~**Requires #204 is merged first**~
* Uses os-conf to add an "external cert" during the pre-start deploy stage
* Also adds linting for acceptance-tests
* Also fixes bug that causes invalid cert bundles when there is more than one `crt_list` entry and `ext_crt_list` is present
=> Add acceptance tests for `ext_crt_list_policy: fail` and fix cert packing bug

acceptance-tests/bosh_helpers.go, acceptance-tests/config.go, acceptance-tests/https_ext_crt_list_test.go
~**Requires #206 is merged first**~
Verifies that external certificates installed _after_ monit starts the HAPRoxy wrapper script but before _ ext_crt_list_timeout_ expires work correctly
=> Test ext_crt_policy fail with delayed external certificate installation

acceptance-tests/master_cli_test.go, jobs/haproxy/spec, jobs/haproxy/templates/haproxy_wrapper.erb
Adds two new properties:
`master_cli_enable` (default `false`)
`master_cli_bind` (default `127.0.0.1:9001`)
With documentation in `spec` and an acceptance test
Master CLI allows managing HAProxy https://cbonte.github.io/haproxy-dconv/2.4/management.html#9.4
=> Add properties to enable HAProxy master CLI

jobs/haproxy/spec, jobs/haproxy/templates/blacklist_cidrs.txt.erb, jobs/haproxy/templates/haproxy.config.erb, jobs/haproxy/templates/reload.erb, jobs/haproxy/templates/trusted_domain_cidrs.txt.erb, jobs/haproxy/templates/whitelist_cidrs.txt.erb, spec/haproxy/templates/haproxy_config/backend_http_routed_spec.rb, spec/haproxy/templates/haproxy_config/backend_http_spec.rb, spec/haproxy/templates/haproxy_config/backend_tcp_spec.rb, spec/haproxy/templates/haproxy_config/frontend_cf_tcp_routing_spec.rb, spec/haproxy/templates/haproxy_config/frontend_http_spec.rb, spec/haproxy/templates/haproxy_config/frontend_https_spec.rb, spec/haproxy/templates/haproxy_config/frontend_tcp_spec.rb, spec/haproxy/templates/haproxy_config/frontend_wss_spec.rb, spec/haproxy/templates/trusted_domain_cidrs.txt_spec.rb
~**Requires #207 is merged first**~
These are a series of small changes aimed at:
1. Improving specs where there may be some confusion
2. Preventing the user from accidentally configuring properties in an inconsistent way
Changes:
* Document fact that `trusted_domain_cidrs` can be b64-encoded gzipped cidr list file
* Fix bug where TCP check port is invalid if `port` is provided but `backend_port` is not
* Removed unnecessary `then` keywords in erb templates (`then` is only needed for one-liners)
* If SSL host verification is enabled, it will error if SSL verification is not enabled
* If HSTS is disabled, it will error if HSTS preload or HSTS subdomains are set
* If `drain_frontend_grace_time` is non-zero it will error if `drain_enable` is not true
* Update `tcp` spec to document …
=> Miscellaneous UX improvements

acceptance-tests/domain_fronting_test.go, jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy/templates/haproxy_config/frontend_https_spec.rb, spec/haproxy/templates/haproxy_config/frontend_wss_spec.rb
[Domain Fronting](https://en.wikipedia.org/wiki/Domain_fronting) allows clients to set a host name different from the SNI value when connecting to a HTTPS-protected host.
This allows CDNs to serve hundreds of pages under the same domain without having to provide a valid certificate for each of them.
For example, a client could make this call:
```
curl -H "cute-puppies.com" https://big-cdn.com
```
To fetch the website of cute-puppies.com from the CDN.
A second usage of domain fronting is avoiding censorship. Since the HTTP host header is part of the L7 which is encrypted, the censor can only see the SNI value which is not.
By passing a non-blocked SNI value to the served and a host header to blocked content, a client can bypass censorship effectively.
There is a catch, of course.
When …
=> Add option for disabling domain fronting

acceptance-tests/xfcc_test.go, jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy/templates/haproxy_config/frontend_https_spec.rb, spec/haproxy/templates/haproxy_config/frontend_wss_spec.rb
Changes:
* `X-SSL-Client-*` headers describing client certificate will only be added when `ha_proxy.forwarded_client_cert` also requires that the `X-Forwarded-Client-Cert` is overwritten with the client certificate info.
* `X-SSL-Client-*` headers will be stripped from incoming requests if `ha_proxy.forwarded_client_cert` is `sanitize_set`
* Update spec to clarify when `X-SSL-Client-*` headers are added / overwritten
* Refactor `ha_proxy.config` to simplify `ha_proxy.forwarded_client_cert` implementation
* Update `ha_proxy.config` websockets  frontend `X-SSL-Client-*` header behaviour to match https frontend behaviour
* Update units tests to test new functionality and to fix following mistake: Unit tests mistakenly [stated](https://github.com/cloudfoundry-incubator/haproxy-boshrelease/blob …
=> All XFCC headers should respect ha_proxy.forwarded_client_cert property

acceptance-tests/mtls_frontend_test.go
Adds mTLS acceptance test which verifies that client certificates may only be used with the intended SNIs
=> Add mTLS acceptance tests for domain-specific mTLS certs

acceptance-tests/domain_fronting_test.go, acceptance-tests/http.go, acceptance-tests/https_ext_crt_list_test.go, acceptance-tests/https_frontend_test.go, acceptance-tests/mtls_frontend_test.go, acceptance-tests/xfcc_test.go, jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy/templates/haproxy_config/frontend_https_spec.rb, spec/haproxy/templates/haproxy_config/frontend_wss_spec.rb
`ha_proxy.disable_domain_fronting` should not require an SNI. However when an SNI is provided, it should reject mismatched Host and SNI.
* This update also fixes the SNI check so that a Host header that includes the optional port suffix (`myhost.com:443`) is checked correctly.
* This update also adds an option to `ha_proxy.disable_domain_fronting` so that domain fronting is only checked for mtls connections
=> Do not require SNIs when disable_domain_fronting is true

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy/templates/haproxy_config/global_and_default_options_spec.rb
This allows consumers to disable TLSv1.2 in an environment where they require TLSv1.3+.
=> Allow disabling TLSv1.2

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy/templates/haproxy_config/global_and_default_options_spec.rb
This allows consumers to disable TLSv1.3 in an environment where they require < TLSv1.3.
=> Allow disabling TLSv1.3

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy/templates/haproxy_config/global_and_default_options_spec.rb
~Requires https://github.com/cloudfoundry-incubator/haproxy-boshrelease/pull/233 is merged first as this has a dependency on HAProxy 2.4+~
Adds `lua_scripts_per_thread` property which corresponds to HAProxy new `lua-load-per-thread` config property.
Existing `lua_scripts` property remains unchanged.
Also updates spec with caveats from HAProxy docs about use of [lua-load](https://cbonte.github.io/haproxy-dconv/2.4/configuration.html#lua-load) and [lua-load-per-thread](https://cbonte.github.io/haproxy-dconv/2.4/configuration.html#lua-load-per-thread).
These changes have been tested manually (`lua_scripts` and `lua_scripts_per_thread` don't seem complex enough to require an acceptance tests since the BOSH release doesn't do much other than pass the configuration values straight to the …
=> Add lua_scripts_per_thread property

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy/templates/haproxy_config/frontend_https_spec.rb, spec/haproxy/templates/haproxy_config/frontend_wss_spec.rb
This will allow us to forward non-verifying mTLS certificates to a proper ACL or lua script later.
It seems, only `crt-ignore-err` doesn't catch all possible errors and you can still end up with `tlsv1 alert unknown ca` errors that don't tell you anything.
=> Also ignore ca errors when ignoring crt errors

ci/scripts/shipit, haproxy-patches/disable-rfc-6455-compliance.patch, packages/haproxy/packaging
This ships an alternative HAProxy release which skips RFC 6455 compliance. When using this release, websocket requests to HAProxy will not be checked for the `sec-websocket-key` header, which was introduced as a check in HAProxy 2.4.0
=> Create alternative release which allows hot patching of haproxy code

acceptance-tests/config.go, acceptance-tests/domain_fronting_test.go, acceptance-tests/http.go, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy/templates/haproxy_config/frontend_https_spec.rb, spec/haproxy/templates/haproxy_config/frontend_wss_spec.rb
Host header and SNI case should be ignored when checking for domain fronting
Also fixes acceptance test config parsing error checking
=> Ignore host header and SNI case when checking domain fronting

ci/scripts/shipit
rename patched release to prevent accidental glob match in s3 file upload
=> rename patched release to prevent accidental glob match in s3 file upload

acceptance-tests/https_frontend_test.go, jobs/haproxy/spec, jobs/haproxy/templates/certs.ttar.erb, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy/templates/certs.ttar_spec.rb, spec/haproxy/templates/haproxy_config/global_and_default_options_spec.rb
added fields:
- ha_proxy.ssl_ciphersuites sets ssl-default-bind-ciphersuites
and ssl-default-server-ciphersuites
- ha_proxy.crt_list[].ssl_ciphersuites sets the corresponding
fields in the CRT list
=> add support for TLSv1.3 ciphersuites

jobs/haproxy/monit, jobs/haproxy/spec
Added a flag to separate monit healthchecks configuration from the other
healthchecks, thus enabling us to test the platform on the cases that we
are starting up.
Co-authored-by: Claire Tinati <ctinati@vmware.com>
Co-authored-by: Jhonathan Aristizabal <jhonathana@vmware.com>
=> Added a flag to separate monit healthchecks from backend health checks

ci/pipeline.yml
Concourse github resource is broken due to:
https://github.com/concourse/github-release-resource/issues/108
https://github.com/concourse/github-release-resource/pull/107
This PR implements this fix https://github.com/concourse/github-release-resource/pull/107#issuecomment-919194641 until we get around to updating Concourse to 7.5.0+
=> temporarily use latest concourse/github-release-resource resource until Concourse is updated to 7.5.0+

.gitignore, jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy/templates/haproxy_config/backend_http_routed_spec.rb, spec/haproxy/templates/haproxy_config/backend_http_spec.rb
Adds new properties `backend_health_fall` and `backend_health_rise` for backend health checks.
Currently rise and fall are not set on the backend server health checks. If the parameters are not set, HAProxy defaults the values to `fall 3 rise 2`
https://cbonte.github.io/haproxy-dconv/2.4/configuration.html#5.2-fall
https://cbonte.github.io/haproxy-dconv/2.4/configuration.html#5.2-rise
This PR will expose these options for backend health checks (anywhere where `backend_use_http_health` is set to true), while setting the default values to match the HAProxy defaults above.
=> Expose rise and fall healthchk options

ci/release_notes.md
Release notes for 11.8.0 - adding the `backend_health_fall` and `backend_health_rise` options to backend health checks.
=> Add release notes for 11.8.0

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy/templates/haproxy_config/frontend_http_spec.rb, spec/haproxy/templates/haproxy_config/frontend_https_spec.rb, spec/haproxy/templates/haproxy_config/frontend_wss_spec.rb
For use as a general reverse proxy it is useful to be able to route based on more than just `path_beg`. This should be a no-op change for most users but provide a way to configure additional routing rules for backends through a new `additional_acls` property.
This PR is split into 2 commits as I wasn't sure if adding `_0` to the (default) `path_beg` acl made sense or whether to just leave it without a suffix and start numbering the additional acls only. I think I prefer handling them all the same way personally. The PR can be squashed if this is preferred.
=> Additional backend acls

acceptance-tests/xfcc_test.go, ci/release_notes.md, jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy/templates/haproxy_config/frontend_https_spec.rb, spec/haproxy/templates/haproxy_config/frontend_wss_spec.rb
Reverts the X-Forwarded-Client-Chain feature released in https://github.com/cloudfoundry/haproxy-boshrelease/releases/tag/v11.9.1.  This increased the header size of some requests which caused backend servers for users to hit header limits
=> Revert X-Forwarded-Client-Chain

acceptance-tests/acceptance_tests_suite_test.go, acceptance-tests/access_control_test.go, acceptance-tests/backend_match_http_protocol_test.go, acceptance-tests/bosh_helpers.go, acceptance-tests/buffer_size_test.go, acceptance-tests/config.go, acceptance-tests/domain_fronting_test.go, acceptance-tests/healthcheck_test.go, acceptance-tests/http_frontend_test.go, acceptance-tests/https_ext_crt_list_test.go, acceptance-tests/https_frontend_test.go, acceptance-tests/keepalived_test.go, acceptance-tests/master_cli_test.go, acceptance-tests/mtls_frontend_test.go, acceptance-tests/remote.go, acceptance-tests/strict_sni_test.go, acceptance-tests/tcp_frontend_test.go, acceptance-tests/websocket_test.go, acceptance-tests/xenial_test.go, acceptance-tests/xfcc_test.go, ci/scripts/acceptance-tests
The acceptance tests currently take around 50 minutes to run.
The first 10 minutes of this is deploying the BOSH director using BOSH lite. This can't be easily parallelized.
The next 40 minutes is the tests themselves where we deploy HAProxy to the BOSH lite director in different configurations. This PR parallelizes this process via the `ginkgo -p` [flag](https://onsi.github.io/ginkgo/#parallel-specs) which by default uses one thread per CPU when run on a machine with four or fewer CPUs, or CPUs - 1 when run on a machine with more than four CPUs. It uses seven threads on our Concourse CI server. Note that the HAProxy deployments now need unique names per thread (although deployments in the same thread can reuse the deployment name).
This change reduces the test execution time from 40 …
=> Parallelize acceptance tests

acceptance-tests/regex_acl_test.go, packages/haproxy/packaging
**Regex based ACLs were not working at all**. The regex engine for HAproxy, PCRE2 was silently failing, causing all regex-based ACLs to not match. Adding the --enable-jit option when compiling PCRE2 fixes the issue.
This PR also adds an acceptance test to catch future regressions.
=> Fix HAProxy regex support regression

ci/scripts/shipit, ci/scripts/update-manifest
Replaces the SHA1 key for releases on the release page with the SHA256 hash.
=> Add SHA-256 for the Release page

acceptance-tests/strict_sni_test.go, ci/release_notes.md, config/blobs.yml, jobs/haproxy/templates/haproxy.config.erb, packages/haproxy/packaging, spec/haproxy/templates/haproxy_config/frontend_cf_tcp_routing_spec.rb, spec/haproxy/templates/haproxy_config/frontend_http_spec.rb, spec/haproxy/templates/haproxy_config/frontend_https_spec.rb, spec/haproxy/templates/haproxy_config/frontend_tcp_spec.rb, spec/haproxy/templates/haproxy_config/frontend_wss_spec.rb, spec/haproxy/templates/haproxy_config/global_and_default_options_spec.rb, spec/haproxy/templates/haproxy_config/healthcheck_listener_spec.rb
The upgrade required changing how the 'grace' keyword is used within the haproxy config. Previously it was added to each indvidual frontend, now it must be enabled as a global option. See the blow documentation from HAProxy for details.
https://www.haproxy.com/blog/announcing-haproxy-2-5/#graceful-stop-of-all-proxies
https://cbonte.github.io/haproxy-dconv/2.5/configuration.html#grace
=> Update HAProxy version to 2.5.4

config/blobs.yml, packages/keepalived/packaging, packages/keepalived/spec
This bumps the version of keepalived as version 2.2.2 has a vulnerability as noted in the below link.
[CVE-2021-44225](https://nvd.nist.gov/vuln/detail/CVE-2021-44225)
=> [CVE-2021-44225] Bump keepalived to 2.2.7 from 2.2.2

ci/release_notes.md
This is the release notes that bumps the keepalived version to 2.2.7 from 2.2.2.
=> Add release notes

jobs/haproxy/templates/haproxy_wrapper.erb
This waits for the main HAProxy process' PID instead of waiting indefinitely.
When the main process goes down, HAProxy will be restarted automatically by BPM.
=> Wait for the main HAProxy process in daemon mode

jobs/haproxy/templates/haproxy_wrapper.erb
When logs are rotated with logrotate using copytruncate haproxy does not
reset the offset and keeps writing from the old offset prepending logs
with null bytes. This results in HAProxy logs growing indefinetely.
Redirect output to pipe and let cat write to log file.
#284
=> Resolve the null bytes in log file after rotation

ci/scripts/shipit, packages/keepalived/packaging
The upstream release version (e.g. HAProxy) contained in an `haproxy-boshrelease` are not evident from its version number.
This change introduces a table of version numbers contained in a particular boshrelease. The version numbers are automatically taken from `packages/*/packaging` and should be representative.
=> Add upstream version numbers for contained components in release information

ci/release_notes.md, config/blobs.yml, packages/haproxy/packaging
Fixes CVE-2022-1586 and CVE-2022-1587
=> Bump PCRE2 to version 10.40

jobs/haproxy/templates/haproxy_wrapper.erb
This applies the same logic for fixing monit restarts after HAproxy crashes to when HAproxy has been reloaded.
=> Fix infinite sleep after reload

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, jobs/haproxy/templates/haproxy_wrapper.erb, spec/haproxy/templates/haproxy_config/global_and_default_options_spec.rb, spec/haproxy/templates/haproxy_config/stats_listener_spec.rb
As of version 2.5 HAProxy no longer supports the nbproc global option. We
therefore remove it from this bosh release as well.
=> fix(haproxy)!: remove nbproc property

ci/pipeline.yml
The term 'approved' is overloaded with general PR approval.
This change makes it clear that the label enables automated PR validation via CI.
=> Prepare for renaming label `approved` to `run-ci`

Gemfile.lock, acceptance-tests/acceptance_tests_suite_test.go, acceptance-tests/bosh_helpers.go, acceptance-tests/drain_test.go, acceptance-tests/go.mod, jobs/haproxy/spec, jobs/haproxy/templates/drain.erb, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy/templates/drain_spec.rb, spec/haproxy/templates/haproxy_config/global_and_default_options_spec.rb, spec/haproxy/templates/haproxy_config/healthcheck_listener_spec.rb
- Remove grace keyword as it is unsafe to use with reloads ( see [docs section](https://docs.haproxy.org/2.5/configuration.html#grace) )
- Shutdown health check externally via socket api
- Clear separation between grace time and drain time:
- grace = health check down, listeners up. new connections are still accepted
- drain = listeners down, new connections are refused, old connections still handled
- We no longer run both grace and drain in parallel, but rather first shut down health checks and sleep for grace period, THEN shut down listeners and tell BOSH to wait for drain period.
- During reloads, nothing changes on the health checks (line has been removed)
- This should prevent health check problems during reload as well as
- Improve speed of reloads as the handover of old …
=> Fix reload grace

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 5.4.3 to version 5.4.4, downloaded from https://www.lua.org/ftp/lua-5.4.4.tar.gz.
=> Bump lua version to 5.4.4

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.5.7 to version 2.5.8, downloaded from http://www.haproxy.org/download/2.5/src/haproxy-2.5.8.tar.gz.
=> Bump haproxy version to 2.5.8

ci/pipeline.yml
they got lost while reverting a whitespace-changing commit
=> Re-add credential vars for AWS/GitHub for autobump

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 1.7.4.1 to version 1.7.4.3, downloaded from http://www.dest-unreach.org/socat/download/socat-1.7.4.3.tar.gz.
=> Bump socat version to 1.7.4.3

acceptance-tests/bosh_helpers.go, ci/README.md
There was little documentation on this so far. The new README should help new and returning developers get into the acceptance test setup and its specifics more easily.
=> Add documentation for the CI and acceptance test setup

acceptance-tests/drain_test.go, jobs/haproxy/templates/drain.erb, spec/haproxy/templates/drain_spec.rb
We encountered an issue during deployment phase. Bosh filed to drain on canary VM. 
```
Task 6224192 | 23:51:20 | L executing pre-stop: ha_proxy_z2/16e2782c-adcd-4e88-b5b4-e064c9911c57 (0) (canary)
Task 6224192 | 23:51:20 | L executing drain: ha_proxy_z2/16e2782c-adcd-4e88-b5b4-e064c9911c57 (0) (canary) (00:00:03)
L Error: Action Failed get_task: Task b5e5ccc7-02af-4fc6-508c-f31d95f95749 result: 1 of 2 drain scripts failed. Failed Jobs: haproxy. Successful Jobs: syslog_forwarder.
Task 6224192 | 23:51:22 | Error: Action Failed get_task: Task b5e5ccc7-02af-4fc6-508c-f31d95f95749 result: 1 of 2 drain scripts failed. Failed Jobs: haproxy. Successful Jobs: syslog_forwarder.
Task 6224192 Started  Tue Aug 23 23:50:51 UTC 2022
Task 6224192 Finished Tue Aug 23 23:51:22 UTC 2022
Task 6224192 …
```
=> fixes drain script failure when HAproxy not running and pidfile present

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.5.8 to version 2.6.5, downloaded from https://www.haproxy.org/download/2.6/src/haproxy-2.6.5.tar.gz.
=> Bump haproxy version to 2.6.5

acceptance-tests/README.md, acceptance-tests/run-local.sh, ci/pipeline.yml, ci/scripts/start-bosh.sh
Docker for Mac changed to using cgroups v2 by default.
These instructions help set it back to v1, as BOSH lite and the docker-cpi do not run with cgroups v2.
=> Fix local docker mac acceptance

ci/scripts/shipit
With the autobumper we've added the URL origins for specific versions after the version number. The release notes appender in `shipit` did not filter those out and created a messy Release page.
This fixes the version number extraction to include only the version number, not the comment behind it.
=> Keep only the version number for the release note, not the comment after

README.md, acceptance-tests/rate_limit_test.go, ci/release_notes.md, docs/rate_limiting.md, jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy/templates/haproxy_config/rate_limit_spec.rb
Allow configuration of rate-limits based on connection rate and request
rate. Each limit and it's details can be fine tuned for the given
use-case.
See `docs/rate_limiting.md` for examples/configuration.
Co-Authored-By: Alexander Nicke <alexander.nicke@sap.com>
=> feat: rate-limiting support

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.6.5 to version 2.6.6, downloaded from https://www.haproxy.org/download/2.6/src/haproxy-2.6.6.tar.gz.
=> Bump haproxy version to 2.6.6

.gitignore, acceptance-tests/.gitignore, acceptance-tests/README.md, acceptance-tests/acceptance_tests_suite_test.go, acceptance-tests/bionic_test.go, acceptance-tests/go.mod, acceptance-tests/go.sum, acceptance-tests/mtls_frontend_test.go, acceptance-tests/run-local.sh, ci/Dockerfile, ci/pipeline.yml, ci/scripts/acceptance-tests, ci/scripts/shell, ci/scripts/start-bosh.sh, manifests/haproxy.yml, manifests/ops-files/no-backend.yml
- Added convenience methods for local testing (docker socket, bosh env)
- Added ops-file for testing haproxy deploy w/o backend needed
- Bumped ssh client to deal with SHA1 no longer working as a signature algo
- Bumped BPM to v1.1.19 to fix logging issues on jammy
- Updated test for xenial to test for bionic (n-1 test)
=> Update release to jammy stemcell

acceptance-tests/bosh_helpers.go, acceptance-tests/crash_test.go, acceptance-tests/drain_test.go, jobs/haproxy/spec, jobs/haproxy/templates/drain.erb, jobs/haproxy/templates/haproxy.config.erb, jobs/haproxy/templates/haproxy_wrapper.erb, spec/haproxy/templates/drain_spec.rb, spec/haproxy/templates/haproxy_config/global_and_default_options_spec.rb
This should prevent idle connections from being terminated immediately during restarts/reloads.
The default is to enable to option as this used to be the default behavior prior to 2.4 and was changed silently.
We also have a default value for hard-stop-after so enabling the option by default should be safe.
Changes:
- idle-close-on-response enabled by default (HAproxy will gracefully close idle conns now, instead of closing them outright)
- draining will no longer cause HAproxy to be restarted by monit after it has terminated itself
- the draining process is now handled completely within the drain script. BOSH wait time is set to 0.
- HAproxy will still be restarted after crashes unrelated to draining
- made the unit tests for the drain script less strict and error-prone
=> Add Idle close on response option

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 1.7.4.3 to version 1.7.4.4, downloaded from http://www.dest-unreach.org/socat/download/socat-1.7.4.4.tar.gz.
=> Bump socat version to 1.7.4.4

acceptance-tests/healthcheck_test.go, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy/templates/haproxy_config/healthcheck_listener_spec.rb
This PR fixes a bug with the Azure load balancer that prevents it from recognizing this HAproxy instance as unhealthy during draining.
The setting forces a "connection: close" from HAproxy as well as a FIN sent to the client. This forces the load balancer to open a new connection on every health check, which won't be possible during draining, because the listener will have been disabled by then.
The result is that the Azure load balancer immediately acknowledges this HAproxy as unhealthy and will stop sending new connections to it.
=> Close connection on health checks

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.6.6 to version 2.6.7, downloaded from https://www.haproxy.org/download/2.6/src/haproxy-2.6.7.tar.gz.
=> Bump haproxy version to 2.6.7

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 10.40 to version 10.42, downloaded from https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.42/pcre2-10.42.tar.gz.
=> Bump pcre2 version to 10.42

ci/scripts/autobump-dependencies.py
This should fix the problems with hatop not having a `*.tar.gz` asset
we will probably also have to fix the packaging script for hatop as we no longer have a tar gz to unpack
=> Add filename_suffix to support hatop assets

config/blobs.yml, packages/haproxy/packaging, packages/haproxy/spec
Automatic bump from version 0.8.1 to version 0.8.2, downloaded from https://github.com/jhunt/hatop/releases/download/v0.8.2/hatop.
=> Bump hatop version to 0.8.2

ci/scripts/autobump-dependencies.py
Preparation for HAProxy 2.7.x upgrade.
=> ci(autobumper): allow haproxy 2.7

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.6.7 to version 2.7.1, downloaded from https://www.haproxy.org/download/2.7/src/haproxy-2.7.1.tar.gz.
=> Bump haproxy version to 2.7.1

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.7.1 to version 2.7.2, downloaded from https://www.haproxy.org/download/2.7/src/haproxy-2.7.2.tar.gz.
=> Bump haproxy version to 2.7.2

ci/scripts/shipit
The release text only contains the SHA1/SHA256 hashes for the regular release.
We also produce a patched release. This PR adds the SHA hashes for the patched release to the release text, which should make consuming it easier.
=> Add SHA1/SHA256 hashes for the patched release to the release text

jobs/haproxy/spec
This commit changes the documentation that stated the separator for multiple error codes would be a pipe but it actually is a comma.
See: https://docs.haproxy.org/2.7/configuration.html#5.1-ca-ignore-err
=> doc: fix description of client_cert_ignore_err

ci/pipeline.yml, config/blobs.yml, config/final.yml
AWS S3 keys were rotated. The WG also moved to GCS for storage.
Added a new bucket `haproxy-boshrelease` on the account "App-Runtime-Platform-WG".
This PR uses this new bucket for version tracking and release uploads.
=> Move CI blobstore to GCS

ci/scripts/shipit
Yaml padding broke in #356 after addressing review comments and running into a bash limitation (no variable expansion in sequence literals)
=> Shipit: Fix incorrect YAML padding

ci/scripts/shipit
The release note appending deployment information tried to access the SHA for the patched release before that patched release was built.
Related: #357 #356 
Fixes: #351
=> fix(shipit): Correct order of patched version SHA in release note

ci/release_notes.md, config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.6.7 to version 2.6.9, downloaded from https://www.haproxy.org/download/2.6/src/haproxy-2.6.9.tar.gz.
=> Bump haproxy version to 2.6.9

ci/pipeline.yml, ci/scripts/autobump-dependencies.py
The move to GCS did not address the autobumper. This PR now does.
Also fix support for alternative branches for PRs (branch-off point and non-conflicting autobumper branch name)
=> fix(autobumper): update to use the GCS bucket

ci/release_notes_template.md
Contributors are shown by github, no extra section needed
=> Remove acknowledgement from release notes template

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.7.3 to version 2.7.4, downloaded from https://www.haproxy.org/download/2.7/src/haproxy-2.7.4.tar.gz.
=> Bump haproxy version to 2.7.4

ci/release_notes.md, config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.7.4 to version 2.7.5, downloaded from https://www.haproxy.org/download/2.7/src/haproxy-2.7.5.tar.gz.
=> Bump haproxy version to 2.7.5

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.7.5 to version 2.7.6, downloaded from https://www.haproxy.org/download/2.7/src/haproxy-2.7.6.tar.gz.
=> Bump haproxy version to 2.7.6

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.6.9 to version 2.6.12, downloaded from https://www.haproxy.org/download/2.6/src/haproxy-2.6.12.tar.gz.
=> Bump haproxy version to 2.6.12

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.7.6 to version 2.7.7, downloaded from https://www.haproxy.org/download/2.7/src/haproxy-2.7.7.tar.gz.
=> Bump haproxy version to 2.7.7

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.7.7 to version 2.7.8, downloaded from https://www.haproxy.org/download/2.7/src/haproxy-2.7.8.tar.gz.
=> Bump haproxy version to 2.7.8

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 5.4.4 to version 5.4.5, downloaded from https://www.lua.org/ftp/lua-5.4.5.tar.gz.
=> Bump lua version to 5.4.5

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.6.12 to version 2.6.13, downloaded from https://www.haproxy.org/download/2.6/src/haproxy-2.6.13.tar.gz.
=> Bump haproxy version to 2.6.13

ci/pipeline.yml
Check works fine now. No patched resource needed anymore.
=> ci: remove github-release-alt resource type

config/blobs.yml, packages/keepalived/packaging
Automatic bump from version 2.2.7 to version 2.2.8, downloaded from https://keepalived.org/software/keepalived-2.2.8.tar.gz.
=> Bump keepalived version to 2.2.8

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.7.8 to version 2.7.9, downloaded from https://www.haproxy.org/download/2.7/src/haproxy-2.7.9.tar.gz.
=> Bump haproxy version to 2.7.9

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.6.13 to version 2.6.14, downloaded from https://www.haproxy.org/download/2.6/src/haproxy-2.6.14.tar.gz.
=> Bump haproxy version to 2.6.14

ci/pipeline-haproxy-maintenance.yml, ci/pipeline.yml
- CI can now only be triggered with both "run-ci" label and a fresh approval by one of the code owners
- approvals will be revoked on code changes
- tested successfully on https://github.com/cloudfoundry/haproxy-boshrelease/pull/474
- pipeline already patched
=> fix(ci): only trigger ci on approved PRs

ci/README.md, ci/pipeline-haproxy-maintenance.yml, ci/pipeline.yml
- Add "wg-app-runtime-platform-networking-extensions-approvers" to trusted_teams
- Add dependabot and CFN-CI to trusted_users
in order to trigger CI pipeline for PRs authored by members of the WG or technical users mentioned above without any approvals.
=> ci: use trusted_teams for git-pull-requests

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.6.14 to version 2.6.15, downloaded from https://www.haproxy.org/download/2.6/src/haproxy-2.6.15.tar.gz.
=> Bump haproxy version to 2.6.15

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.7.9 to version 2.7.10, downloaded from https://www.haproxy.org/download/2.7/src/haproxy-2.7.10.tar.gz.
=> Bump haproxy version to 2.7.10

ci/release_notes.md
Add a release note for 12.2.0 (HAProxy 2.7.10) and other version bumps.
=> Release note for 12.2.0 (HAProxy 2.7.10)

ci/pipeline.yml, ci/scripts/shipit
The `shipit` script creates commits as part of the release process and pushes them to the `master` branch.
The author of the commit must be excluded from the branch protection from the master branch. This is only the case for our bot users.
This change allows setting the git username / e-mail to the botuser (maintained in the vars.yml for the pipeline)
=> ci(shipit): use a bot account for creating release commits

ci/pipeline.yml
Use the GitHub token instead of an SSH key for the `git` resource.
This is already active on the pipeline.
=> ci(pipeline): use the GitHub token for git checkouts

ci/pipeline-haproxy-maintenance.yml
same treatment as with main branch
=> ci: remove ssh key from maintenance branch

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.7.10 to version 2.8.3, downloaded from https://www.haproxy.org/download/2.8/src/haproxy-2.8.3.tar.gz.
=> Bump haproxy version to 2.8.3

ci/scripts/autobump-dependencies.py
Allow to update haproxy 2.7 on maintenance branch
=> ci(autobump): allow haproxy 2.7 on maintenance branch

jobs/haproxy/templates/haproxy.config.erb, spec/haproxy/templates/haproxy_config/frontend_https_spec.rb, spec/haproxy/templates/haproxy_config/frontend_wss_spec.rb
Previously we manually converted the host header by splitting it on the colon and making it lower case.
This commit switches to the host_only sample which is meant to do exactly that.
See: https://docs.haproxy.org/2.6/configuration.html#7.3.1-host_only
=> refactor: use host_only converter

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.8.3 to version 2.8.4, downloaded from https://www.haproxy.org/download/2.8/src/haproxy-2.8.4.tar.gz.
=> Bump haproxy version to 2.8.4

ci/release_notes.md
Same content like in https://github.com/cloudfoundry/haproxy-boshrelease/pull/572.
Docker on the CI had some issues resolving github and could not push. After a retry, the docker container was also cleaned up. To reduce the efforts, we simply create a new release (after fixing the DNS issues)
=> Create release_notes for 13.3.0

acceptance-tests/acceptance_tests_suite_test.go, acceptance-tests/bosh_helpers.go, acceptance-tests/remote.go, acceptance-tests/retry_redispatch_test.go, jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy/templates/haproxy_config/global_and_default_options_spec.rb
Without retries and redispatch enabled, failing backends produce an outage to the client.
The redispatch option allows HAProxy to try another backend instead of failing the request.
- Adds the option to retry failed connections to backends
- Adds the option to redispatch to other backends on failed connects
- Checks that retries are configured if redispatch is enabled
- Also, the test framework was updated so that it supports more than one backend per HAProxy.
=> feat: Enable redispatch to different server on retry

ci/scripts/autobump-dependencies.py
This should prevent mis-haps like #588 and #589.
=> ci(autobumper): skip github pre-releases

ci/pipeline-haproxy-maintenance.yml, ci/pipeline.yml
Concourse is not the best when it comes to PR validations. To reduce the amount of stuck builds and PRs this commit de-couples the two checks. This might result in more wasted builds on the acceptance tests which are expensive, but the current situation which requires manually triggering the checks is much worse.
=> ci: de-couple unit and acceptance tests

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 10.42 to version 10.43, downloaded from https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.43/pcre2-10.43.tar.gz.
=> Bump pcre2 version to 10.43

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.8.6 to version 2.8.7, downloaded from https://www.haproxy.org/download/2.8/src/haproxy-2.8.7.tar.gz.
=> Bump haproxy version to 2.8.7

ci/pipeline.yml, ci/scripts/acceptance-tests
the `.git/resource/changed_files` file exists only on PRs
=> fix: only skip PRs not regular acceptance tests

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.8.7 to version 2.8.9, downloaded from https://www.haproxy.org/download/2.8/src/haproxy-2.8.9.tar.gz.
=> Bump haproxy version to 2.8.9

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy/templates/haproxy_config/raw_blocks_spec.rb
Proper formatting of indented multiline configurations, new raw blocks: listen, frontend, backend.
=> new raw blocks: listen, frontend, backend

ci/pipeline.yml
Problem:
It is not possible for the CFN-CI bot to bypass the branch protection rules. This is due to the fact that this user is no admin on this repo here.
Solution
Make use of a deploy key added to this repo within the git-resources.
=> ci: use ssh key for CFN-CI bot in concourse pipeline

ci/release_notes.md
=> ci: add release notes

ci/scripts/autobump-dependencies.py
Updates the auto-bumper for socat from pinned version 1.7.x to 1.x.
Also pulls up the various pinned versions to the top of the script where they are easier to find.
=> Auto-bump socat to 1.x.y

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 1.7.4.4 to version 1.8.0.0, downloaded from http://www.dest-unreach.org/socat/download/socat-1.8.0.0.tar.gz.
=> Bump socat version to 1.8.0.0

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.8.9 to version 2.8.10, downloaded from https://www.haproxy.org/download/2.8/src/haproxy-2.8.10.tar.gz.
=> Bump haproxy version to 2.8.10

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 10.43 to version 10.44, downloaded from https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.44/pcre2-10.44.tar.gz.
=> Bump pcre2 version to 10.44

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 5.4.6 to version 5.4.7, downloaded from https://www.lua.org/ftp/lua-5.4.7.tar.gz.
=> Bump lua version to 5.4.7

acceptance-tests/headers_test.go, jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy/templates/haproxy_config/frontend_http_spec.rb, spec/haproxy/templates/haproxy_config/frontend_https_spec.rb, spec/haproxy/templates/haproxy_config/frontend_wss_spec.rb
Implement config property strip_headers, which allows to delete configured headers from incoming requests based on the header key.
If both 'strip_headers' and 'headers' contain the same key, the header (if set) is first deleted from the request, and then set to the configured value.
=> Add strip_header to delete headers on the frontend

config/blobs.yml, packages/keepalived/packaging
Automatic bump from version 2.2.8 to version 2.3.1, downloaded from https://keepalived.org/software/keepalived-2.3.1.tar.gz.
=> Bump keepalived version to 2.3.1

ci/release_notes.md
According to versioning guide: https://github.com/cloudfoundry/haproxy-boshrelease/tree/master/ci#versioning-guide
=> Create release_notes for v14.3.0+2.8.10

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy/templates/haproxy_config/backend_http_spec.rb
Hello haproxy people,
CF Gorouter wants to switch to TLS healthchecks. I tested out if the HAProxy works with it. I found the issue that unless you tell it explicitly to only use TLS for health checks it will run into TLS issues (namely not using it). THis PR aims to add an option to enable check-ssl (https://docs.haproxy.org/2.4/configuration.html#5.2-check-ssl) to the release.
I tested it working by hand originally on our staging and made a PR to replicate the setup with the bosh release. The Linter and test suite are green and without complaints. I also added a simple test for the property.
=> Adding option to check backend health via TLS

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 1.8.0.0 to version 1.8.0.1, downloaded from http://www.dest-unreach.org/socat/download/socat-1.8.0.1.tar.gz.
=> Bump socat version to 1.8.0.1

ci/scripts/start-bosh.sh
Do not set -e, because then we trap service docker stop and docker never starts. Instead keep waiting.
=> fix: docker startup in acceptance

acceptance-tests/proxy_protocol_test.go, jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
`expect_proxy_cidrs` is used for dynamically determining whether proxy protocol should be used or not. On AWS the health check and regular traffic are forwarded with or without proxy protocol.
The idea of adding the `expect-proxy` directive CIDRs for AWS load balancer IP addresses as a "marker" for traffic that should become Proxy Protocol, while other traffic (including transparently proxied traffic) remains without Proxy Protocol.
By adding a new health endpoint, when `expect_proxy_cidrs` is set, the operator can select, which endpoint to use for checking the health of HAProxy.
=> fix(expect-proxy): provide alternative health endpoint for expect_proxy_cidrs

config/blobs.yml, packages/keepalived/packaging
Automatic bump from version 2.3.1 to version 2.3.2, downloaded from https://keepalived.org/software/keepalived-2.3.2.tar.gz.
=> Bump keepalived version to 2.3.2

ci/pipeline.yml
The `drafts: true` parameter was set on the job, but should be set on the resource.
=> shipit draft release

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.8.11 to version 2.8.12, downloaded from https://www.haproxy.org/download/2.8/src/haproxy-2.8.12.tar.gz.
=> Bump haproxy version to 2.8.12

ci/.gitignore, ci/pipeline.yml, ci/upload-to-concourse.sh
Build new image when there is new docker-cpi image, or when we change image config.
Build daily to bring updated os dependencies.
Use new image in the pipeline.
=> Periodically build and use testflight image

ci/pipeline.yml
Instead of depending on custom image, use standard cf community github pr resource.
=> ci: Use cfcommunity/github-pr-resource

.github/workflows/stale.yml
I initially thought the days-before-close is relative to the last activity on the PR but it seems to be relative to the time the stale label was added. I lowered it to 15 days to achieve the actual desired time of 45 days before closing an item.
=> fix: set correct close time

jobs/haproxy/templates/haproxy.config.erb, spec/haproxy/templates/haproxy_config/frontend_tcp_spec.rb
`expect_proxy_cidrs` handling is now added to TCP frontends
=> fix: enable expect_proxy_cidrs handling in tcp backends

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.8.12 to version 2.8.13, downloaded from https://www.haproxy.org/download/2.8/src/haproxy-2.8.13.tar.gz.
=> Bump haproxy version to 2.8.13

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 1.8.0.1 to version 1.8.0.2, downloaded from http://www.dest-unreach.org/socat/download/socat-1.8.0.2.tar.gz.
=> Bump socat version to 1.8.0.2

acceptance-tests/.gitignore, acceptance-tests/run-local.sh, ci/scripts/acceptance-tests, ci/scripts/shell
Few minor fixes to acceptance test scripts and setup so that they can run fine on localhost running linux.
=> Fix acceptance test setup to work on local linux

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.8.13 to version 2.8.14, downloaded from https://www.haproxy.org/download/2.8/src/haproxy-2.8.14.tar.gz.
=> Bump haproxy version to 2.8.14

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 10.44 to version 10.45, downloaded from https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.45/pcre2-10.45.tar.gz.
=> Bump pcre2 version to 10.45

acceptance-tests/headers_test.go, jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy/templates/haproxy_config/frontend_http_spec.rb, spec/haproxy/templates/haproxy_config/frontend_https_spec.rb
Add property `ha_proxy.true_client_ip_header`. This property allows to define a header name that stores the client [src](https://www.haproxy.com/documentation/haproxy-configuration-manual/latest/#src) IP address, as seen by HAProxy.
=> Add parameter to set a header containing the client ip

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy/templates/haproxy_config/backend_http_spec.rb
This PR introduces a property that enables more fine-grained configuration of a specific backend.
=> implement configurable http-reuse feature

ci/.ci-ignore
When a new[ release is released,](https://github.com/cloudfoundry/haproxy-boshrelease/commit/05469c6fb317103d4ca7cedc754374e2e7a7e800) there are some updates to `.final_builds` and similar. Skip CI, as to create new release, things had to be merged first, meaning they have passed CI.
Cleanup ci-ignore - remove old files.
=> Skip ci tests (unit, acceptance) on new releases being pushed

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 1.8.0.2 to version 1.8.0.3, downloaded from http://www.dest-unreach.org/socat/download/socat-1.8.0.3.tar.gz.
=> Bump socat version to 1.8.0.3

config/blobs.yml, packages/keepalived/packaging
Automatic bump from version 2.3.2 to version 2.3.3, downloaded from https://keepalived.org/software/keepalived-2.3.3.tar.gz.
=> Bump keepalived version to 2.3.3

.gitignore, acceptance-tests/README.md, acceptance-tests/run-local.sh, acceptance-tests/run-shell.sh, ci/compilation.yml, ci/pipeline.yml, ci/scripts/acceptance-tests, ci/scripts/functions-ci.sh, ci/scripts/lint, ci/scripts/shell, ci/scripts/start-bosh.sh, ci/scripts/unit-tests, ci/scripts/update-blob, ci/scripts/update-manifest
Fix tech debt on acceptance tests:
- remove unused bpm
Improve runtime/user friendliness for development and debug:
- use local/cached testflight image
- DRY wrapper scripts
- run with "dirty" git
- add persistence for containers (bosh stays running)
- optimise speed (compilation = 2, working overlay2 in bosh docker for internal docker)
- apply shellcheck recommended fixes
Update docs.
=> Improve acceptance tests

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.8.14 to version 2.8.15, downloaded from https://www.haproxy.org/download/2.8/src/haproxy-2.8.15.tar.gz.
=> Bump haproxy version to 2.8.15

jobs/haproxy/templates/drain.erb, spec/haproxy/templates/drain_spec.rb
When there is no HTTP health-check for a TCP frontend the drain logic doesn't work as the frontend it tries to disable does not exist. This commit makes the statement to disable the frontend during the draining depend on whether the HTTP health-heck for that TCP frontend is enbaled and if not excludes the drain logic for it.
Resolves: https://github.com/cloudfoundry/haproxy-boshrelease/issues/788
=> fix: properly check if TCP should be drained

docs/release-process.md
Add documentation on the release process.
=> doc: add release process doc

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 5.4.7 to version 5.4.8, downloaded from https://www.lua.org/ftp/lua-5.4.8.tar.gz.
=> Bump lua version to 5.4.8

config/blobs.yml, packages/keepalived/packaging
Automatic bump from version 2.3.3 to version 2.3.4, downloaded from https://keepalived.org/software/keepalived-2.3.4.tar.gz.
=> Bump keepalived version to 2.3.4

ci/pipeline.yml, ci/scripts/autobump-dependencies.py
Include version diff (changelog) into automatically created PRs for haproxy bumps.
=> Add changelog to haproxy autobump PRs

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 10.45 to version 10.46, downloaded from https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.46/pcre2-10.46.tar.gz.
=> Bump pcre2 version to 10.46

config/blobs.yml, packages/haproxy/packaging
Automatic bump from version 2.8.15 to version 2.8.16, downloaded from https://www.haproxy.org/download/2.8/src/haproxy-2.8.16.tar.gz.
[Changelog for HAProxy 2.8.16](https://www.haproxy.org/download/2.8/src/CHANGELOG).
Please also check list of [known open bugs for HAProxy 2.8.16](https://www.haproxy.org/bugs/bugs-2.8.16.html).
The developer's summary for this release can be found in [the Announcement post for the HAProxy 2.8.16 release](https://www.mail-archive.com/search?l=haproxy%40formilux.org&q=announce+subject%3A%22[ANNOUNCE]+haproxy-2.8.16%22+-subject%3A%22re:%22).
<details>
<summary>HAPROXY CHANGELOG between 2.8.16 and 2.8.15</summary>
```
2025/10/03 : 2.8.16
- BUG/MINOR: cli: Issue an error when too many args …
```
=> Bump haproxy version to 2.8.16
