jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
Signed-off-by: Claudia Beresford <claudia@cloudcredo.com>
=> enable logging to remote servers

templates/infrastructure-openstack.yml, templates/make_manifest
Enable this release to be deployed on openstack
=> Add templates to support openstack infrastructure

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, templates/example-settings.yml
- Default accet-proxy to empty string
- Allow accept-proxy to be configured by user “accept-proxy”
- Added example settings
=> Added accept-proxy config for bind

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, packages/haproxy/packaging, packages/haproxy/spec
Hi,
we need the DNS resolution feature of v1.6. I updated to the latest version from the webside and added the config option. If you like to merge just download the package.
Cheers
Johannes
=> Update to version 1.6.10 (latest) version and DNS Resolution feature

jobs/haproxy/spec, jobs/haproxy/templates/backend-ca-certs.erb, jobs/haproxy/templates/haproxy.config.erb
For users that really want hop by hop SSL termination.
=> Enable SSL backends with CA cert verification

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
=> Added template and defaults for PFS

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
Please don't merge yet, since I need to sign and send the CLA to the foundation. Anyway @geofffranks can you please tell me how it looks?
Issue #49 
Thanks,
Leandro.-
PS: I haven't enabled it for WSS because the [IETF Spec](https://tools.ietf.org/html/rfc6797) establish this only for HTTP.
=> HSTS support

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
I would like to build VM with multiple ethernet. But did not find option to bind a specified IP. So provided this property
=> Enable ha proxy to have bind ip

jobs/haproxy/templates/haproxy.config.erb
Signed-off-by: Josh Winters <jwinters@pivotal.io>
=> Adding support for the tcp backend_port setting in non-statically mapped backends

README.md, manifests/haproxy.yml
=> bosh2 deploy manifests/haproxy.yml

ci/pipeline.yml, ci/scripts/shipit, ci/scripts/testflight, ci/scripts/update-blob
@geofffranks there was a bug in `ci/scripts/testflight` where it used the wrong value for which `network` to use in deployment; this is a fix.
This PR will also send notifications to slack when you `shipit` successfully.
I've already `ci/repipe` these changes to CI.
=> correctly use cloud-config network

jobs/haproxy/spec
For ha_proxy.client_cert_ignore_err in the job spec
=> Fix #82: Update documentation and examples

jobs/haproxy/templates/haproxy.config.erb
Related to https://github.com/cloudfoundry-incubator/haproxy-boshrelease/pull/96
- Allow configuration of TLS without mutual auth
- Cleanup "== true"
- Remove accept-proxy from non-TLS frontends
- Convert value part of custom headers to string
- Prettify output and format of the template
@geofffranks please take a look
=> Addon to pull-request #96

ci/release_notes.md, jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, packages/haproxy/packaging, packages/haproxy/spec
Yes, I realize I don't have the blobs.
Signed-off-by: David Bishop <dbisj@allstate.com>
=> Add lua support, add custom haproxy config support

ci/release_notes.md, jobs/haproxy/templates/haproxy.config.erb
Cool your jets, man.
Signed-off-by: Geoff Franks <Geoff.Franks@allstate.com>
=> Fix typo in haproxy template for CF-specific TCP router

Gemfile, Gemfile.lock, README.md, jobs/haproxy/spec, jobs/haproxy/templates/error503.http.erb, jobs/haproxy/templates/haproxy.config.erb, jobs/haproxy/templates/pre-start.erb, spec/haproxy_templates_spec.rb
=> Added errorfile template for 503

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb
Described in issue https://github.com/cloudfoundry-incubator/haproxy-boshrelease/issues/149
=> Make the length of log message configurable

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy_templates_spec.rb
=> Define timeout retry and resolve_retries in resolver section

ci/release_notes.md
=> Add 10.4.0 release notes

ci/.gitignore, ci/pipeline-plain.yml, ci/release_notes_template.md, ci/upload-to-concourse.sh
Add pipeline for new CI with plain yml (no spruce dependency)
=> Pipeline plain

jobs/haproxy/spec, jobs/haproxy/templates/haproxy.config.erb, spec/haproxy_templates_spec.rb
=> Tcp custom health port

acceptance-tests/xfcc_test.go
Accidentally broke the build :(
=> Fix xfcc test failure

acceptance-tests/go.mod, acceptance-tests/go.sum, acceptance-tests/http.go, acceptance-tests/https_frontend_test.go, acceptance-tests/remote.go
~**Requires #205 is merged first**~
Adds an acceptance test for HTTP2 via https
=> HTTP2 ALPN acceptance test

acceptance-tests/domain_fronting_test.go, acceptance-tests/http.go
Add an acceptance test to verify that requests with no header still result in a 400 even if domain fronting is blocked
=> Acceptance test: verify that requests with no header still result in a 400 even if domain fronting is blocked

ci/pipeline.yml
=> Use teliaoss/github-pr-resource instead

acceptance-tests/README.md, acceptance-tests/acceptance_tests_suite_test.go, acceptance-tests/https_ext_crt_list_test.go, acceptance-tests/mtls_frontend_test.go, acceptance-tests/strict_sni_test.go, ci/pipeline.yml, ci/scripts/start-bosh.sh, manifests/haproxy.yml
=> switch to bionic stemcell

ci/release_notes.md
Add Release Notes for the new release 11.3.0
=> Release Notes 11.3.0

ci/pipeline.yml
dont want to match patched release
=> fix shipit s3 file regex matching

acceptance-tests/go.mod, ci/pipeline.yml, docs/mutual_tls.md, manifests/haproxy.yml
Update reference to git repo to point to new org
This has already been tested by manually updating the concourse pipeline with the changes.
=> update git repo references to point to new location

ci/release_notes.md, ci/release_notes_template.md
please comment / approve. no need to run pipeline
=> add release notes for v11.13.0

acceptance-tests/acceptance_tests_suite_test.go, acceptance-tests/lua_test.go
Add an integration test that installs and checks a small Lua service (applet) that returns the current Lua version.
The Lua version is also output to the test's result outputs as provided by the server.
=> Lua acceptance test

ci/scripts/autobump-dependencies.py
=> Use download_url instead of url for assets

ci/pipeline-haproxy-maintenance.yml
Builds on top of https://github.com/cloudfoundry/haproxy-boshrelease/pull/414
=> clean(ci): remove unused pipeline resource

ci/release_notes.md
To trigger the CI and test github access with test-patch release (v12.2.1+2.7.10)
=> Create empty release_notes.md to test CI

.github/dependabot.yml
Limit number of open PRs to prevent parallel concourse runs
=> ci: limit number of open PRs

ci/README.md, ci/upload-to-concourse.sh
Update upload script and README to reflect recent changes with concourse server.
=> Update CI information
